name = "How to pyscript"

# packages = ["numpy", "sympy"]
#
# [files]
# "./palettes.py" = ""
# "./fractals.py" = ""

[js_modules.main]
"https://cdn.datatables.net/1.13.7/js/jquery.dataTables.js" = "datatables"
